const choferes=[
    {
        "nombre": "Nombre1",
        "apellido": "Apellido1",
        "correoElectronico": "correo1@example.com",
        "fechaNacimiento": "2022-01-01T12:00",
        "dni": 123456789,
        "numeroCelular": 987654321,
        "fotoChofer": "ruta/foto1.jpg",
        "aeropuertoOrigen": "Talara",
        "servicioOfrecido": "auto",
        "modeloVehiculo": "Modelo1",
        "numeroPlaca": "ABC123",
        "licenciaManejo": "Licencia1",
        "fotoVehiculo": "ruta/foto_vehiculo1.jpg",
        "fechaNacSoat": "2022-01-01T12:00",
        "permisoCirculacion": "ruta/permiso1.pdf",
        "maxPasajeros": 4
    },
    {
        "nombre": "Nombre2",
        "apellido": "Apellido2",
        "correoElectronico": "correo2@example.com",
        "fechaNacimiento": "2022-02-02T12:00",
        "dni": 234567890,
        "numeroCelular": 876543210,
        "fotoChofer": "ruta/foto2.jpg",
        "aeropuertoOrigen": "Tumbes",
        "servicioOfrecido": "vans",
        "modeloVehiculo": "Modelo2",
        "numeroPlaca": "DEF456",
        "licenciaManejo": "Licencia2",
        "fotoVehiculo": "ruta/foto_vehiculo2.jpg",
        "fechaNacSoat": "2022-02-02T12:00",
        "permisoCirculacion": "ruta/permiso2.pdf",
        "maxPasajeros": 6
    },
    {
        "nombre": "Nombre3",
        "apellido": "Apellido3",
        "correoElectronico": "correo3@example.com",
        "fechaNacimiento": "2022-03-03T12:00",
        "dni": 345678901,
        "numeroCelular": 765432109,
        "fotoChofer": "ruta/foto3.jpg",
        "aeropuertoOrigen": "Lima",
        "servicioOfrecido": "auto",
        "modeloVehiculo": "Modelo3",
        "numeroPlaca": "GHI789",
        "licenciaManejo": "Licencia3",
        "fotoVehiculo": "ruta/foto_vehiculo3.jpg",
        "fechaNacSoat": "2022-03-03T12:00",
        "permisoCirculacion": "ruta/permiso3.pdf",
        "maxPasajeros": 5
      },
      {
        "nombre": "Nombre4",
        "apellido": "Apellido4",
        "correoElectronico": "correo4@example.com",
        "fechaNacimiento": "2022-04-04T12:00",
        "dni": 456789012,
        "numeroCelular": 654321098,
        "fotoChofer": "ruta/foto4.jpg",
        "aeropuertoOrigen": "Cusco",
        "servicioOfrecido": "vans",
        "modeloVehiculo": "Modelo4",
        "numeroPlaca": "JKL012",
        "licenciaManejo": "Licencia4",
        "fotoVehiculo": "ruta/foto_vehiculo4.jpg",
        "fechaNacSoat": "2022-04-04T12:00",
        "permisoCirculacion": "ruta/permiso4.pdf",
        "maxPasajeros": 7
      },
      {
        "nombre": "Nombre5",
        "apellido": "Apellido5",
        "correoElectronico": "correo5@example.com",
        "fechaNacimiento": "2022-05-05T12:00",
        "dni": 567890123,
        "numeroCelular": 543210987,
        "fotoChofer": "ruta/foto5.jpg",
        "aeropuertoOrigen": "Arequipa",
        "servicioOfrecido": "auto",
        "modeloVehiculo": "Modelo5",
        "numeroPlaca": "MNO456",
        "licenciaManejo": "Licencia5",
        "fotoVehiculo": "ruta/foto_vehiculo5.jpg",
        "fechaNacSoat": "2022-05-05T12:00",
        "permisoCirculacion": "ruta/permiso5.pdf",
        "maxPasajeros": 4
      }
]

export default choferes;